import { DashboardCalendar } from "@/features/dashboard-calendar";
import type { ScheduledPost } from "@/types/database";

function daysFromNow(offset: number) {
  return new Date(Date.now() + offset * 86400000).toISOString();
}

const MOCK_POSTS: ScheduledPost[] = [
  {
    id: "post-1",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "feed",
    media_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
    caption: "Descubra o ScanPlates! O app que analisa suas refeições com IA.",
    scheduled_at: daysFromNow(0),
    status: "published",
    ig_media_id: null,
    published_at: daysFromNow(0),
    error_message: null,
    reach: 3420,
    likes: 287,
    comments: 43,
    shares: 61,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-2",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "story_image",
    media_url: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400",
    caption: "Já experimentou o ScanPlates? Link na bio!",
    scheduled_at: daysFromNow(0),
    status: "published",
    ig_media_id: null,
    published_at: daysFromNow(0),
    error_message: null,
    reach: 1890,
    likes: 124,
    comments: 12,
    shares: 28,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-3",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "feed",
    media_url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400",
    caption: "Alimentação saudável ficou mais fácil com ScanPlates. Teste grátis!",
    scheduled_at: daysFromNow(1),
    status: "pending",
    ig_media_id: null,
    published_at: null,
    error_message: null,
    reach: null,
    likes: null,
    comments: null,
    shares: null,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-4",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "story_video",
    media_url: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=400",
    caption: "Receita do dia com ScanPlates!",
    scheduled_at: daysFromNow(2),
    status: "pending",
    ig_media_id: null,
    published_at: null,
    error_message: null,
    reach: null,
    likes: null,
    comments: null,
    shares: null,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-5",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "reel",
    media_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400",
    caption: "Como eu uso o ScanPlates no meu dia a dia (Reel)",
    scheduled_at: daysFromNow(3),
    status: "pending",
    ig_media_id: null,
    published_at: null,
    error_message: null,
    reach: null,
    likes: null,
    comments: null,
    shares: null,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-6",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "feed",
    media_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
    caption: "Resultados da semana com ScanPlates!",
    scheduled_at: daysFromNow(5),
    status: "pending",
    ig_media_id: null,
    published_at: null,
    error_message: null,
    reach: null,
    likes: null,
    comments: null,
    shares: null,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-7",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "story_image",
    media_url: "https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=400",
    caption: "Swipe up para testar o ScanPlates!",
    scheduled_at: daysFromNow(5),
    status: "pending",
    ig_media_id: null,
    published_at: null,
    error_message: null,
    reach: null,
    likes: null,
    comments: null,
    shares: null,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-8",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "feed",
    media_url: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400",
    caption: "Minha jornada com nutrição inteligente. ScanPlates",
    scheduled_at: daysFromNow(7),
    status: "pending",
    ig_media_id: null,
    published_at: null,
    error_message: null,
    reach: null,
    likes: null,
    comments: null,
    shares: null,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-9",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "story_video",
    media_url: "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=400",
    caption: "Bastidores: como uso o app antes de cada refeição",
    scheduled_at: daysFromNow(7),
    status: "pending",
    ig_media_id: null,
    published_at: null,
    error_message: null,
    reach: null,
    likes: null,
    comments: null,
    shares: null,
    created_at: "2026-05-18T00:00:00Z",
  },
  {
    id: "post-10",
    profile_id: "user-1",
    brand_id: "brand-1",
    media_type: "feed",
    media_url: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400",
    caption: "Post falhou: erro de teste",
    scheduled_at: daysFromNow(-2),
    status: "failed",
    ig_media_id: null,
    published_at: null,
    error_message: "Token expirado",
    reach: null,
    likes: null,
    comments: null,
    shares: null,
    created_at: "2026-05-16T00:00:00Z",
  },
];

export default function CalendarioPage() {
  return <DashboardCalendar posts={MOCK_POSTS} />;
}
